/*
 * main.c -- IntP eBPF Userspace Loader (V6)
 *
 * Userspace component of the eBPF/CO-RE IntP variant. Responsibilities:
 *   1. Open and load the eBPF object (intp_kern.bpf.o)
 *   2. Set target PID in the eBPF programs
 *   3. Attach eBPF programs to tracepoints and kprobes
 *   4. Read events from the BPF ring buffer
 *   5. Read resctrl for mbw and llcocc (hardware metrics)
 *   6. Aggregate metrics over sampling intervals
 *   7. Output in IntP-compatible format
 *
 * Uses the libbpf skeleton pattern:
 *   - intp_kern.skel.h is auto-generated by bpftool gen skeleton
 *   - The skeleton provides type-safe open/load/attach/destroy functions
 *
 * Build: gcc -O2 -o intp-ebpf main.c resctrl/mbw.c resctrl/llcocc.c -lbpf -lelf -lz
 *
 * Usage: sudo ./intp-ebpf -p <PID> -i <interval_ms>
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <getopt.h>
#include <errno.h>
#include <time.h>

/* TODO: Include generated skeleton */
/* #include "intp_kern.skel.h" */
#include "intp_kern.bpf.h"

/* TODO: Include libbpf headers */
/* #include <bpf/libbpf.h> */
/* #include <bpf/bpf.h> */

/* Forward declarations for resctrl readers */
extern int resctrl_mbw_init(pid_t pid, long max_bw_mbps);
extern double resctrl_mbw_sample(void);
extern int resctrl_llcocc_init(pid_t pid, long llc_size_kb);
extern double resctrl_llcocc_sample(void);

/* Aggregated metrics for current interval */
static struct {
    unsigned long long netp_rx_bytes;
    unsigned long long netp_tx_bytes;
    unsigned long long nets_service_ns;
    unsigned long long blk_service_ns;
    unsigned long long blk_count;
    unsigned long long cpu_time_ns;
    unsigned long long llcmr_refs;
    unsigned long long llcmr_misses;
} metrics;

static volatile sig_atomic_t running = 1;

static void sighandler(int sig)
{
    (void)sig;
    running = 0;
}

/*
 * handle_event -- Ring buffer callback for eBPF events
 *
 * Called by libbpf for each event in the ring buffer.
 * Accumulates metric values into the metrics struct.
 */
static int handle_event(void *ctx, void *data, size_t data_sz)
{
    /* TODO: Cast data to struct intp_event */
    /* TODO: Switch on event type and accumulate into metrics */
    (void)ctx;
    (void)data;
    (void)data_sz;
    return 0;
}

static void usage(const char *prog)
{
    fprintf(stderr, "Usage: %s -p <PID> -i <interval_ms> [options]\n", prog);
    fprintf(stderr, "\nOptions:\n");
    fprintf(stderr, "  -p, --pid <PID>          Target process ID\n");
    fprintf(stderr, "  -i, --interval <ms>      Sampling interval in ms\n");
    fprintf(stderr, "  -v, --verbose            Verbose output\n");
    fprintf(stderr, "  -h, --help               Show this help\n");
}

int main(int argc, char *argv[])
{
    pid_t target_pid = 0;
    int interval_ms = 1000;
    int verbose = 0;

    static struct option long_opts[] = {
        {"pid",      required_argument, NULL, 'p'},
        {"interval", required_argument, NULL, 'i'},
        {"verbose",  no_argument,       NULL, 'v'},
        {"help",     no_argument,       NULL, 'h'},
        {NULL, 0, NULL, 0}
    };

    int opt;
    while ((opt = getopt_long(argc, argv, "p:i:vh", long_opts, NULL)) != -1) {
        switch (opt) {
        case 'p':
            target_pid = (pid_t)atoi(optarg);
            break;
        case 'i':
            interval_ms = atoi(optarg);
            break;
        case 'v':
            verbose = 1;
            break;
        case 'h':
        default:
            usage(argv[0]);
            return (opt == 'h') ? 0 : 1;
        }
    }

    if (target_pid <= 0) {
        fprintf(stderr, "Error: valid PID required (-p)\n");
        usage(argv[0]);
        return 1;
    }

    (void)verbose;

    /* TODO: Step 1 -- Open BPF skeleton */
    /* struct intp_kern_bpf *skel = intp_kern_bpf__open(); */
    /* if (!skel) { perror("open skeleton"); return 1; } */

    /* TODO: Step 2 -- Set target PID before loading */
    /* skel->rodata->target_pid = target_pid; */

    /* TODO: Step 3 -- Load BPF programs into kernel */
    /* if (intp_kern_bpf__load(skel)) { perror("load"); return 1; } */

    /* TODO: Step 4 -- Attach programs to tracepoints/kprobes */
    /* if (intp_kern_bpf__attach(skel)) { perror("attach"); return 1; } */

    /* TODO: Step 5 -- Set up ring buffer consumer */
    /* struct ring_buffer *rb = ring_buffer__new( */
    /*     bpf_map__fd(skel->maps.events), handle_event, NULL, NULL); */

    /* TODO: Step 6 -- Initialize resctrl readers */
    /* resctrl_mbw_init(target_pid, detect_mem_bw_mbps()); */
    /* resctrl_llcocc_init(target_pid, detect_llc_size_kb()); */

    signal(SIGINT, sighandler);
    signal(SIGTERM, sighandler);

    printf("# IntP eBPF profiler -- PID %d, interval %d ms\n",
           target_pid, interval_ms);
    printf("# netp  nets  blk  mbw  llcmr  llcocc  cpu\n");

    struct timespec sleep_ts = {
        .tv_sec  = interval_ms / 1000,
        .tv_nsec = (interval_ms % 1000) * 1000000L
    };

    while (running) {
        /* TODO: Poll ring buffer for new events */
        /* ring_buffer__poll(rb, 100); */

        nanosleep(&sleep_ts, NULL);

        /* TODO: Drain remaining events */
        /* ring_buffer__consume(rb); */

        /* TODO: Read hardware metrics from resctrl */
        /* double mbw = resctrl_mbw_sample(); */
        /* double llcocc = resctrl_llcocc_sample(); */

        /* TODO: Compute and output all metrics */
        /* TODO: Reset metrics struct for next interval */
        memset(&metrics, 0, sizeof(metrics));
    }

    /* TODO: Cleanup */
    /* ring_buffer__free(rb); */
    /* intp_kern_bpf__destroy(skel); */

    printf("# IntP eBPF profiler stopped\n");
    return 0;
}
