/*
 * vmlinux.h -- Kernel Type Definitions (PLACEHOLDER)
 *
 * This file is auto-generated from the running kernel's BTF data.
 * It contains ALL kernel struct, enum, and typedef definitions needed
 * by the eBPF programs to access kernel data structures via CO-RE.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * To generate:
 *   bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
 *
 * Prerequisites:
 *   - Kernel built with CONFIG_DEBUG_INFO_BTF=y
 *   - bpftool installed (apt install linux-tools-common)
 *   - /sys/kernel/btf/vmlinux must exist
 *
 * This placeholder will be replaced by the actual generated header
 * during the build process (see Makefile).
 *
 * The generated file is typically 5-10 MB and contains definitions for
 * all kernel types. Key types used by IntP eBPF programs include:
 *
 *   - struct sk_buff (networking: netp, nets)
 *   - struct request (block I/O: blk)
 *   - struct task_struct (scheduling: cpu)
 *   - struct perf_event (performance counters: llcmr)
 */

#ifndef __VMLINUX_H__
#define __VMLINUX_H__

/* Placeholder -- replaced by bpftool btf dump during build */
#error "vmlinux.h must be generated. Run: make vmlinux"

#endif /* __VMLINUX_H__ */
